name = "DWave"
uuid = "4d534982-bf11-4157-9e48-fe3a62208a50"
authors = ["pedromxavier <pedroxavier@psr-inc.com>", "pedroripper <pedroripper@psr-inc.com>"]
version = "0.4.1"

[deps]
Graphs = "86223c79-3864-5bf0-83f7-82e725a168b6"
MathOptInterface = "b8f27783-ece8-5eb3-8dc8-9495eed66fee"
PythonCall = "6099a3de-0909-46bc-b1f4-468b9a2dfc0d"
QUBODrivers = "a3f166f7-2cd3-47b6-9e1e-6fbfe0449eb0"
QUBOTools = "60eb5b62-0a39-4ddc-84c5-97d2adff9319"

[compat]
Graphs = "1"
MathOptInterface = "1"
PythonCall = "0.9.15"
QUBODrivers = "0.3"
QUBOTools = "0.9"
julia = "1.9"
