name = "DWave"
uuid = "4d534982-bf11-4157-9e48-fe3a62208a50"
authors = ["pedromxavier <pedroxavier@psr-inc.com>", "pedroripper <pedroripper@psr-inc.com>"]
version = "0.4.0"

[deps]
PythonCall = "6099a3de-0909-46bc-b1f4-468b9a2dfc0d"
QUBODrivers = "a3f166f7-2cd3-47b6-9e1e-6fbfe0449eb0"

[compat]
PythonCall = "0.9.14"
QUBODrivers = "0.3"
julia = "1.9"
